# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install Ubuntu Packages
      run: |
        sudo apt-get -y install tcsh
    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install .
    - name: Test with pytest
      run: |
        rm -r komodoenv  # Remove sources
        pytest tests
