# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6
    - name: Install Ubuntu Packages
      run: |
        sudo apt-get -y install tcsh python3-venv python3.8-venv
    - name: Install Python Packages
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install flake8 pytest
        pip install .
    - name: Test with pytest
      run: |
        rm -r komodoenv  # Remove sources
        pytest tests
