name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install Ubuntu Packages
        run: |
          sudo apt-get -y install tcsh
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt update
          sudo apt install python3.11 python3.11-venv
      - name: Install Python Packages
        run: |
          pip install -U pip
          pip install pytest
          pip install .
      - name: Test with pytest
        run: |
          pytest -sv tests
