name: CI Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_call:

jobs:
  tests:
    name: "Python ${{ matrix.python-version }}"
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install Ubuntu Packages
        run: |
          sudo apt-get -y install tcsh
      - name: Install Python Packages
        run: |
          pip install -U pip
          pip install pytest
          pip install .
      - name: Test with pytest
        run: |
          rm -r komodoenv  # Remove sources
          pytest tests
